matrix:
    include:
        - language: go
          go: "1.10.x"
          before_install:
            - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            - dep ensure -v
          script:
            - go test ./... -v
            - go build main.go
        - language: node_js
          node_js: "stable"
          before_script:
            - cd client
          cache:
            directories:
                - node_modules
          script:
              - npm install
              - npm run build

