matrix:
    include:
        - language: node_js
          node_js: "stable"
          before_script:
            - cd client
          cache:
            directories:
                - node_modules
          script:
              - npm install
              - npm run build

